<style>
    table{
        border-collapse: collapse;
    }
    th{
        font-weight: bolder;
        border-bottom: 2px solid black;
        border-right: 2px solid black;
        padding: .6rem;
    }
    td{
        border: 1px solid black;
        text-align: center;
    }
    td.ico i{
        cursor: pointer;
    }
</style>
<h1>Musculos</h1>

<form  action="<?php echo empty($this->view->muscle['id_muscle']) ? '/muscle/add' : '/muscle/update' ?>" method="POST">
    
    <input type="text" name="muscle" value="<?php echo $this->view->muscle['muscle'] ?>" placeholder="Nome do musculo">
    <input type="hidden" name="id" value="<?php echo $this->view->muscle['id_muscle'] ?>">
    <?php if(!empty($this->view->muscle['muscle'])) {?>
        <input type="submit" value="Editar Musculo">
    <?php }else{ ?>
        <input type="submit" value="Adicionar Musculo">
    <?php } ?>
</form>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Ativo</th>
            <th>Musculo</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->view->muscles as $key => $muscle) {?>
            <tr>
                <td><?php echo $key+1 ?></td>
                <?php if($muscle['ativo']){ ?>
                    <td><input type="checkbox" id="ativo_<?php echo $muscle['id_muscle'] ?>" checked onchange="alterarAtivo('muscle',<?php echo $muscle['id_muscle'] ?>, 0)"></td>
                <?php }else{ ?>
                    <td><input type="checkbox" id="ativo_<?php echo $muscle['id_muscle'] ?>" onchange=" alterarAtivo('muscle',<?php echo $muscle['id_muscle'] ?>, 1)"></td>
                <?php } ?>
                <td><?php echo $muscle['muscle'] ?></td>
                <td class="ico">
                    <a href="/muscle/delete?id=<?php echo $muscle['id_muscle'] ?>"><i class="fa fa-close"></i></a>
                    <a href="/muscles?id=<?php echo $muscle['id_muscle'] ?>"><i class="fa-solid fa-pen"></i></a>
                </td>
            </tr>
        <?php } ?>
        
    </tbody>
</table>
