<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <title><?php echo $this->view->title ?></title>
</head>
<body>
    <?php $this->content() ?>
</body>

<script>
    const alterarAtivo = (item, idItem, ativo) => {
        $.ajax({
            method: "POST",
            url: "/alterarAtivo",
            data: { item: item, idItem: idItem, ativo:ativo }
        }).done(function(msg){
            if(msg == ""){
                $(`#ativo_${idItem}`).attr('onchange', (item, idItem, !ativo))
                console.log(msg)
            }
        })
    }
</script>

</html>